In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.Tensor(5, 3)
print(x)


 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  7.0065e-45  0.0000e+00
 0.0000e+00  0.0000e+00  5.2891e+23
-4.5185e+06  3.5193e-35  1.4013e-45
 0.0000e+00  0.0000e+00 -4.3860e-18
[torch.FloatTensor of size 5x3]



In [3]:
x = torch.rand(5, 3)
print(x)


 0.7575  0.8131  0.1630
 0.7850  0.5271  0.2175
 0.3600  0.4690  0.1428
 0.8344  0.9727  0.5049
 0.7652  0.6073  0.6034
[torch.FloatTensor of size 5x3]



In [4]:
print(x.size())

torch.Size([5, 3])


In [5]:
y = torch.rand(5, 3)
print(x + y)


 1.6954  0.9863  0.8790
 1.4130  1.2538  1.1223
 0.9566  0.7600  0.5726
 1.5806  1.0900  0.8487
 0.8401  1.2214  1.4844
[torch.FloatTensor of size 5x3]



In [6]:
print(torch.add(x, y))


 1.6954  0.9863  0.8790
 1.4130  1.2538  1.1223
 0.9566  0.7600  0.5726
 1.5806  1.0900  0.8487
 0.8401  1.2214  1.4844
[torch.FloatTensor of size 5x3]



In [7]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 1.6954  0.9863  0.8790
 1.4130  1.2538  1.1223
 0.9566  0.7600  0.5726
 1.5806  1.0900  0.8487
 0.8401  1.2214  1.4844
[torch.FloatTensor of size 5x3]



In [9]:
y.add_(x)
print(y)


 1.6954  0.9863  0.8790
 1.4130  1.2538  1.1223
 0.9566  0.7600  0.5726
 1.5806  1.0900  0.8487
 0.8401  1.2214  1.4844
[torch.FloatTensor of size 5x3]



In [10]:
print(x[:, 1])


 0.8131
 0.5271
 0.4690
 0.9727
 0.6073
[torch.FloatTensor of size 5]



In [11]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [12]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [13]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [14]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [15]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [17]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y